stages:

  prepare:
    desc: "Verificar que los datos y modelo existen"
    cmd: echo "Datos OK"
    deps:
      - data/jigsaw/train.csv
      - data/jigsaw/test.csv
      - models/distilbert_toxic

  evaluate:
    desc: "Evaluar modelo pre-entrenado DistilBERT"
    cmd: >
      python src/load_model.py
      --max_length ${eval.max_length}
      --batch_size ${eval.batch_size}
      --model_dir ${eval.output_dir}
    deps:
      - src/load_model.py
      - params.yaml
      - data/jigsaw/train.csv
      - data/jigsaw/test.csv
      - models/distilbert_toxic
    metrics:
      - mlflow_metrics.json:
          cache: false
    params:
      - eval
