stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - data/raw/tweets.csv
    outs:
      - data/processed/

  train:
    cmd: python src/training/train.py
    deps:
      - data/processed/
      - params.yaml
    outs:
      - models/model.pt
