eval:
  model_name: distilbert-base-uncased
  max_length: 128
  val_size: 0.1
  test_size: 0.1
  batch_size: 32
  num_epochs: 3
  learning_rate: 5e-5
  weight_decay: 0.01
  warmup_ratio: 0.1
  seed: 42
  output_dir: models/distilbert_toxic
  num_workers: 2
